### PR TITLE
ConsumerSetting: Add group instance id setter

### PR DESCRIPTION
**Pull request by def1ne**
## Purpose

Update Kafka dependency and add method `withGroupInstanceId` to `ConsumerSettings`.

## References

References #859

### CODE REVIEW

**Comment by ennru** [comment]
Thank you for this PR.
As it changes the Kafka client library version, we won't include it in patch releases, but need to defer it until version 2.0.

Are you aware that you can achieve this feature by overriding the Kafka client library version yourself and setting the property with the `withProperty` method?

**Comment by def1ne** [comment]
We updated kafka client and set property through withProperty. All works fine.

**Comment by ennru** [comment]
I've rebased this PR on master which will go into Alpakka Kafka 2.0.0-M1.

**Comment by ennru** [comment]
Thank you for your contribution!

**Pull request merged**
