### PR TITLE
Testcontainers: make Schema Registry configurable

### LINKED ISSUE #1479: Have to ability to configure the schema registry in the test kit
### Short description
Using the feature "Testing with a Docker Kafka cluster" in the testkit, there is the option the further configure the kafka and the zookeeper using the method `.withConfigureKafka(...)` (for example) (https://doc.akka.io/docs/alpakka-kafka/current/testing-testcontainers.html#settings), but I see there is no option to do the same with the schema registry.

### Details

Add a method to further configure the schema registry i.e. `.withConfigureShemaRegistry(...)`
(I can try to make a PR if this request sound reasonable)

### PR DESCRIPTION
**Pull request by yuvalshi0**
Closes #1479

### CODE REVIEW

**Comment by ennru** [comment]
Please run 'javafmtAll' and commit the reformatted code.

**Comment by yuvalshi0** [comment]
@ennru noob question here, what did the CI break?

**Comment by ennru** [comment]
That was MiMa the detector to avoid changes that at not binary compatible.
The `KafkaTestkitTestcontainersSettings` constructor is private in Scala, but not in byte code.

Please add a file `testkit/src/main/mima-filters/3.0.1.backwards.excludes/PR1489.excludes` with the single line
`ProblemFilters.exclude[DirectMissingMethodProblem]("akka.kafka.testkit.KafkaTestkitTestcontainersSettings.this")`.

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you!

**Comment by yuvalshi0** [comment]
> Thank you!

Thank you for your time!

**Pull request merged**
