### PR TITLE
removed code duplication for examples in documentation

### PR DESCRIPTION
**Pull request by aldenml**
See image
Screen Shot 2021-09-11 at 6 47 37 PM

### CODE REVIEW

**Review by ennru — APPROVED** [review]
Oh, thanks for digging where that came from.
LGTM.

**Comment by ennru** [comment]
The compiler detected unused values (in a different code section 🤷 )
https://github.com/akka/alpakka-kafka/runs/3599581640#step:6:89

Can you clean those, please?

**Comment by aldenml** [comment]
hi @ennru , sure I will look at it

**Comment by aldenml** [comment]
hi @ennru, finally made and pushed the cleanup

**Comment by ennru** [comment]
Thank you.

**Pull request merged**
