### PR TITLE
Handle any combination of Committables in CommitObservationLogic

### LINKED ISSUE #1261: Type cast error in commit observation logic when offsets are pre-batched
### Versions used 

Alpakka Kafka 2.1.0-M1

Akka version: n/a

### Expected Behavior

When the user pre-batches offsets and uses `CommitWhen.NextOffsetObserved` the latest offset for each partition should be deferred.

### Actual Behavior

A type cast runtime exception occurs because Commit When expects single offsets (`CommittableOffset` vs `CommittableOffsetBatch`)

### Relevant logs

```
[ERROR] [18:36:52.431] ak.ac.RepointableActorRef:159 Error in stage [akka.kafka.internal.CommitCollectorStage@25e3cedb]: class akka.kafka.internal.CommittableOffsetBatchImpl cannot be cast to class akka.kafka.ConsumerMessage$CommittableOffset (akka.kafka.internal.CommittableOffsetBatchImpl and akka.kafka.ConsumerMessage$CommittableOffset are in unnamed module of loader 'app')
java.lang.ClassCastException: class akka.kafka.internal.CommittableOffsetBatchImpl cannot be cast to class akka.kafka.ConsumerMessage$CommittableOffset (akka.kafka.internal.CommittableOffsetBatchImpl and akka.kafka.ConsumerMessage$CommittableOffset are in unnamed module of loader 'app')
        at akka.kafka.internal.CommitObservationLogic.updateBatch(CommitObservationLogic.scala:35)
        at akka.kafka.internal.CommitObservationLogic.updateBatch$(CommitObservationLogic.scala:31)
        at akka.kafka.internal.CommitCollectorStageLogic.updateBatch(CommitCollectorStage.scala:35)
        at akka.kafka.internal.CommitCollectorStageLogic.akka$kafka$internal$CommitCollectorStageLogic$$consume(CommitCollectorStage.scala:59)
        at akka.kafka.internal.CommitCollectorStageLogic$$anon$1.onPush(CommitCollectorStage.scala:90)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
```

### Reproducible Test Case

See PR

### PR DESCRIPTION
**Pull request by seglo**
Fixes #1261

### CODE REVIEW

**Comment by seglo** [comment]
I'm not sure why the `verifyDocs` sbt task is failing. I didn't change the line in question.

**Review by ennru — APPROVED** [review]
LGTM.

We should backport this to 2.0.x.

**Comment by seglo** [comment]
> We should backport this to 2.0.x.

Is that to make it easier for Cloudflow to upgrade?

**Comment by ennru** [comment]
I added the label. Let's keep it for the case we do another 2.0.x release.

**Comment by seglo** [comment]
Ok, so no action is required for now?

**Comment by ennru** [comment]
This has been backported to the `release-2.0.x` branch to be part of 2.0.6.

**Pull request merged**
