### PR TITLE
Message loss testcase of #1016

### PR DESCRIPTION
**Pull request by ennru**
The tests for #1016 failed on Travis as the log grows too big. This contains a change to reduce logging.

The original author did not create a separate branch, to run the test on Travis I branched the PR into this.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by seglo** [comment]
Some ideas

* Use `waitUntilConsumerSummary` to block on rebalances instead of `Thread.sleeps`
* Send stream complete signal when a partitioned `Source` receives last message for its partition and await for this to happen (or timeout) instead of cancelling sub sources (raise exception, then `recoverWith`?)
* Run a simple plain consumer on test source data and run consistency checks to confirm no gaps were introduced on the producer side.
* Enable producer idempotence
* Enable producer `DEBUG` logging to see if retries are attempted 
`org.apache.kafka.clients.producer`
* Enable consumer `DEBUG` logging to see what offsets consumers reset to for partitions that get re-assigned

**Comment by jhooda** [comment]
@seglo Thanks for creating the new pull request. From now on, I'll submit any future pull requests on a branch off the master branch. Seems like, for this change we are good for now. If I need to make any changes on this test, I'll submit a pull straight to your fork.

Little bit more background on the test structure. This test suppose to reflect an HA deployment topology. For example, in our deployment topology, each consumer runs on different VM instance (to provide HA). All instances can be stopped or restarted witout losing messages (basically they should be able to handle kill -9 like situation). Any message replay is okay as that is handled by the business logic. There are no gaps/issues introduced on the producer side (one can confirm it via uncommenting producer log statements starting with "produce messages..."). There is an explicit wait on all producer futures to finish publishing before the consumers are started.

Below is some more insights on how offsets are skipped (for a skipped messageId 70381) during rebalance, from test logs: "grep 'topic-8-9-0' my_test_run_loop_29563_81.txt > my_test_run_loop_29563_81_topic-8-9-0.txt" , which is also attached.

1) The first lost message was produced:

16:24:03.954 DEBUG [unning-RebalanceSpec] akka.kafka.scaladsl.RebalanceSpec     produce messages for topicPartition=topic-8-9-0 messageId=70381

2) There was a rabalance around messageId=70380 being consumed by consumer-3, after rebalance offsets were moved back from 379 (end of batch) to 240 for consumer-2
   since offsets jumped back there is no message loss here

16:24:36.786 WARN  [efault-dispatcher-26] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 378 messageId=70379 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:24:36.796 WARN  [efault-dispatcher-26] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 379 messageId=70380 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:24:41.259 DEBUG [default-dispatcher-4] akka.kafka.internal.SubSourceLogic    [bf527#3] Assigning new partitions: topic-8-9-0, topic-1-2-5, topic-6-7-5, topic-5-6-0, topic-5-6-9, topic-2-3-6, topic-7-8-4, topic-5-6-6, topic-7-8-1, topic-2-3-9, topic-10-11-1, topic-7-8-7, topic-3-4-2, topic-9-10-8, topic-2-3-0, topic-5-6-3, topic-6-7-2, topic-9-10-2, topic-3-4-5, topic-3-4-8, topic-8-9-9, topic-2-3-3, topic-1-2-8, topic-4-5-7, topic-4-5-1, topic-9-10-5, topic-4-5-4, topic-8-9-6, topic-6-7-8, topic-10-11-7, topic-8-9-3, topic-1-2-2, topic-10-11-4

16:24:42.597 DEBUG [efault-dispatcher-17] a.k.i.CommittableSubSourceStageLogic  [7329a#1] filtering out messages from revoked partitions Set(topic-8-9-0)

16:24:42.597 DEBUG [efault-dispatcher-17] a.k.i.CommittableSubSourceStageLogic  [7329a#1] filtering out messages from revoked partitions Set(topic-8-9-0)

16:24:43.885 WARN  [efault-dispatcher-29] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 240 messageId=70241 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

16:24:43.895 WARN  [efault-dispatcher-29] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 241 messageId=70242 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

3) so as per above info, messageId 70381 should be at offset 380

4) Another rebalance (this time for consumer-2), after rebalance offset jumped forward from 319 to 400, which caused loss of 20 messages from 
   70381 (offset 380) to 70400 (offset 399)

16:24:47.446 WARN  [efault-dispatcher-17] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 318 messageId=70319 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

16:24:47.456 WARN  [efault-dispatcher-17] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 319 messageId=70320 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

16:24:48.998 INFO  [default-dispatcher-3] a.k.i.CommittableSubSourceStageLogic  [c2c17#3] Starting. Partition topic-8-9-0

16:24:49.343 DEBUG [default-dispatcher-2] akka.kafka.internal.SubSourceLogic    [9ad57#1] Closing SubSources for revoked partitions: topic-8-9-0, topic-7-8-0, topic-5-6-2, topic-9-10-4, topic-5-6-0, topic-2-3-6, topic-7-8-4, topic-10-11-6, topic-5-6-6, topic-7-8-6, topic-4-5-6, topic-3-4-2, topic-9-10-8, topic-2-3-2, topic-3-4-4, topic-8-9-2, topic-2-3-0, topic-6-7-4, topic-6-7-2, topic-9-10-2, topic-4-5-0, topic-3-4-8, topic-1-2-8, topic-10-11-0, topic-8-9-8, topic-2-3-8, topic-4-5-4, topic-5-6-8, topic-1-2-4, topic-8-9-6, topic-6-7-8, topic-1-2-2, topic-10-11-4

16:24:50.381 WARN  [default-dispatcher-4] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 400 messageId=70401 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:24:50.391 WARN  [default-dispatcher-4] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 401 messageId=70402 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

5) some "filtering out..." logs
[my_test_run_loop_29563_81_topic-8-9-0.txt](https://github.com/akka/alpakka-kafka/files/4056762/my_test_run_loop_29563_81_topic-8-9-0.txt)
[my_test_run_loop_29563_81.txt.gz](https://github.com/akka/alpakka-kafka/files/4056764/my_test_run_loop_29563_81.txt.gz)



16:24:53.071 WARN  [efault-dispatcher-25] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 439 messageId=70440 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:24:53.830 INFO  [efault-dispatcher-29] a.k.i.CommittableSubSourceStageLogic  [7329a#1] Completing. Partition topic-8-9-0

16:24:57.411 DEBUG [efault-dispatcher-17] a.k.i.CommittableSubSourceStageLogic  [c2c17#3] filtering out messages from revoked partitions Set(topic-8-9-0)

16:24:57.688 WARN  [efault-dispatcher-29] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 440 messageId=70441 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

5) Another re-balance and offset jumping back from 519 to 500, no message loss here, only message replay

16:25:04.833 WARN  [efault-dispatcher-16] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 518 messageId=70519 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:25:04.843 WARN  [efault-dispatcher-16] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 519 messageId=70520 topicPartition=topic-8-9-0 consumerId=consumer-3 duplicateCount=1

16:25:08.713 INFO  [default-dispatcher-3] a.k.i.CommittableSubSourceStageLogic  [fea7e#2] Starting. Partition topic-8-9-0

16:25:11.593 INFO  [efault-dispatcher-26] akka.kafka.internal.SubSourceLogic    [c4f00#2] Completing. Partitions [topic-9-10-0,topic-8-9-0,topic-7-8-0,topic-6-7-0,topic-5-6-2,topic-9-10-4,topic-5-6-0,topic-2-3-6,topic-7-8-4,topic-10-11-6,topic-5-6-6,topic-7-8-6,topic-6-7-6,topic-1-2-6,topic-2-3-4,topic-4-5-6,topic-4-5-2,topic-4-5-8,topic-3-4-2,topic-9-10-8,topic-8-9-4,topic-2-3-2,topic-7-8-2,topic-10-11-8,topic-3-4-4,topic-8-9-2,topic-3-4-0,topic-6-7-4,topic-4-5-0,topic-10-11-0,topic-8-9-8,topic-2-3-8,topic-5-6-8,topic-1-2-4], StageActor Actor[akka://Spec/system/StreamSupervisor-0/$$Lb#1684226037]

16:25:11.593 INFO  [efault-dispatcher-26] akka.kafka.internal.SubSourceLogic    [c4f00#2] Completing. Partitions [topic-9-10-0,topic-8-9-0,topic-7-8-0,topic-6-7-0,topic-5-6-2,topic-9-10-4,topic-5-6-0,topic-2-3-6,topic-7-8-4,topic-10-11-6,topic-5-6-6,topic-7-8-6,topic-6-7-6,topic-1-2-6,topic-2-3-4,topic-4-5-6,topic-4-5-2,topic-4-5-8,topic-3-4-2,topic-9-10-8,topic-8-9-4,topic-2-3-2,topic-7-8-2,topic-10-11-8,topic-3-4-4,topic-8-9-2,topic-3-4-0,topic-6-7-4,topic-4-5-0,topic-10-11-0,topic-8-9-8,topic-2-3-8,topic-5-6-8,topic-1-2-4], StageActor Actor[akka://Spec/system/StreamSupervisor-0/$$Lb#1684226037]

16:25:12.134 INFO  [efault-dispatcher-29] a.k.i.CommittableSubSourceStageLogic  [fea7e#2] Completing. Partition topic-8-9-0

16:25:12.411 DEBUG [default-dispatcher-3] akka.kafka.internal.SubSourceLogic    [bf527#3] Assigning new partitions: topic-9-10-0, topic-8-9-0, topic-7-8-0, topic-6-7-0, topic-5-6-2, topic-9-10-4, topic-5-6-0, topic-2-3-6, topic-7-8-4, topic-10-11-6, topic-5-6-6, topic-7-8-6, topic-6-7-6, topic-1-2-6, topic-2-3-4, topic-4-5-6, topic-4-5-2, topic-4-5-8, topic-3-4-2, topic-9-10-8, topic-8-9-4, topic-2-3-2, topic-7-8-2, topic-10-11-8, topic-3-4-4, topic-8-9-2, topic-3-4-0, topic-2-3-0, topic-7-8-8, topic-9-10-6, topic-10-11-2, topic-6-7-4, topic-6-7-2, topic-9-10-2, topic-4-5-0, topic-3-4-8, topic-1-2-8, topic-10-11-0, topic-8-9-8, topic-2-3-8, topic-4-5-4, topic-5-6-8, topic-5-6-4, topic-1-2-4, topic-8-9-6, topic-6-7-8, topic-1-2-2, topic-10-11-4, topic-1-2-0, topic-3-4-6

16:25:12.411 INFO  [default-dispatcher-3] a.k.i.CommittableSubSourceStageLogic  [5fa91#3] Starting. Partition topic-8-9-0

16:25:16.269 WARN  [efault-dispatcher-26] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 500 messageId=70501 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

16:25:16.279 WARN  [efault-dispatcher-26] akka.kafka.scaladsl.RebalanceSpec     businessFlow offset 501 messageId=70502 topicPartition=topic-8-9-0 consumerId=consumer-2 duplicateCount=2

**Comment by seglo** [comment]
Thanks, @jhooda.  I think enabling lower log level for `org.apache.kafka.clients.consumer` could reveal more info.  Also, maybe we should update the Alpakka filtering message to include details of offsets that are being filtered.

**Comment by jhooda** [comment]
@seglo I ran the tests with TRACE level logs on looking for the missing messages from offset 460
to 479 (topicPartition topic-2-3-0). (Filtering logs do not show anything being filtered at all.)

03:23:40.525 ERROR [unning-RebalanceSpec] akka.kafka.scaladsl.RebalanceSpec     missing:1: message 10461 topicPartition topic-2-3-0

Only relevant information I found are the following logs where consumer-2 and consumer-3 are simultaneous active and a full block of messages from offset=460 to offset=479 are missing

03:21:51.298 TRACE [efault-dispatcher-17] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-3, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=420, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=440, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}}

03:21:54.829 TRACE [efault-dispatcher-15] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-3, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=440, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=460, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}}

03:22:01.051 TRACE [default-dispatcher-9] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-2, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=360, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=380, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}}

03:22:01.437 TRACE [efault-dispatcher-16] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-2, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=380, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=400, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}}

03:22:07.141 TRACE [efault-dispatcher-11] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-3, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=460, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=480, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}}

03:22:10.057 TRACE [efault-dispatcher-13] o.a.k.c.consumer.internals.Fetcher    [Consumer clientId=consumer-3, groupId=group-1-1] Returning fetched records at offset FetchPosition{offset=480, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} for assigned partition topic-2-3-0 and update position to FetchPosition{offset=500, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=localhost:37391 (id: 0 rack: null), epoch=-1}} 

Since as per above message both consumer-2 and consumer-3 are simultaneous updating FetchPosition there can be some race condition there.

**Comment by seglo** [comment]
@jhooda I spent some time on your test.

I think the main issue was that sub sources emitted by the paritioned source were sometimes not allowed to be fully processed before they were cancelled.  I re-factored the test to emit the sub sources as `RunnableGraphs`, instead of running them from within the stream, so that they can be "drained" before continuing.

The partitioned sources will also re-emit sub sources after they stop (this may not be expected, but it's been the case in Alpakka Kafka since the beginning).  So even though I gave sub sources a condition to stop after the last offset was committed (using `takeWhile`), a new sub source would be emitted by the partitioned source after its predecessor completed.  Therefore it's necessary to track how many partitions have been fully processed and use that as the trigger to cancel the partitioned source before proceeding to assertions of missing records.

I've run your script (renamed to `message_loss.sh` in the root dir) 10 times successfully.  Can you inspect this branch and try it out yourself?  Let me know what you think of the changes I've made.

I also noticed that due to the low `max.poll.records` setting and the business logic processing time delay that messages can take awhile to be processed, so I increased timeouts.

**Comment by jhooda** [comment]
@ennru Thanks a lot for the changes. I ran the test 100 times and as you noted there is no message loss now.

To examine how the topic-partitions are getting consumed by the three consumers, I added some debug statements and sleep statements at various points of code. As per the debug logs I noted some surprise behavior between the six test phases (where each phase lasts for 60.seconds except for the final phase which runs all the way till the end):

1) consumer-1 active
    - only consumer-1 consumes messages
    - Okay, it behaves as expected

2) consumer-1 + consumer-2 active
     - there is no message consumption by either of the consumers
     - Not okay, expectation was both consumer-1 and consumer-2 will consume messages

3) consumer-1 + consumer-2 + consumer-3 active
     - only consumer-3 consuming.
     - Not okay, expectation was all three consumer-1, consumer-2, and consumer-3 will consume messages

4) consumer-1 cancelled AND consumer-2 + consumer-3 active
     - none of the consumers consuming    
     - Not okay, expectation was both consumer-2 and consumer-3 will consume messages

4) consumer-2 cancelled AND consumer-3 active
     - none of the consumers consuming    
     - Not okay, expectation was consumer-3 will consumer messages

5) consumer-2 re-subscribed and active AND consumer-3 active
    - only consumer-2 consuming 
    - Not okay, expectation was both consumer-2 and consumer-3 will consume messages

6) consumer-3 cancelled and AND only consumer-2 active (last phase)
    - only consumer-2 consuming 
    - Okay, behaving as expected

I am not sure why we are getting above behavior. I am attaching a diff of Rebalance.scala for your review. 

Another point I want to mention is as follows:

In production, all three consumers will be running independently in different VMs and will be rebalancing to share topic-partitions and to provide high availability (HA). For HA, they may also come and go abruptly. Is it possible to design the test along those lines? If not then any suggestions on how we'll achieve the objective of load balancing, HA, and no message loss?

[RebalanceSpec.diff.txt](https://github.com/akka/alpakka-kafka/files/4084710/RebalanceSpec.diff.txt)

**Comment by seglo** [comment]
> To examine how the topic-partitions are getting consumed by the three consumers, I added some debug statements and sleep statements at various points of code. As per the debug logs I noted some surprise behavior between the six test phases (where each phase lasts for 60.seconds except for the final phase which runs all the way till the end):
> 
> 1. consumer-1 active
>    
>    * only consumer-1 consumes messages
>    * Okay, it behaves as expected
> 2. consumer-1 + consumer-2 active
>    
>    * there is no message consumption by either of the consumers
>    * Not okay, expectation was both consumer-1 and consumer-2 will consume messages

After each consumer added (except for the last one), you only ever use the `TestProbe` to request `1` `Source` (sub-source).  That means only one partition's `Source` is emitted and run with `runSubSource`.  I believe this was the case before my re-factoring as well.  The consequence is that for every run only the first `Source` that's emitted is consumed.  After each rebalance, some sub-sources may get re-emitted, but some won't.  It's difficult to know in advance what partition each consumer will get because it depends on the rebalance strategy and timing things asynchronously.

I observed that in some cases the first consumer will fully consume a whole partition (1000 messages) before the first rebalance.  In those cases it's possible there is nothing for the rest of the consumers to consume due to the way the sub-sources are requested from the probe, as mentioned above (i.e. if the same fully consumed partition is re-balanced around to consumers).

There's also no delay between when we poll for the correct rebalance state before introducing a new consumer, so as soon as a rebalance completes a new one may be triggered.  In the worst case, it's possible the consumers will never get a chance to fully process and commit messages.  In your original test you had a delay, so if that was re-added (after the rebalance state is confirmed with  `waitUntilConsumerSummary`) that may allow some time for consuming to happen.

> 7. consumer-3 cancelled and AND only consumer-2 active (last phase)
>    
>    * only consumer-2 consuming
>    * Okay, behaving as expected
> 
> I am not sure why we are getting above behavior. I am attaching a diff of Rebalance.scala for your review.
> 
> Another point I want to mention is as follows:
> 
> In production, all three consumers will be running independently in different VMs and will be rebalancing to share topic-partitions and to provide high availability (HA). For HA, they may also come and go abruptly. Is it possible to design the test along those lines? If not then any suggestions on how we'll achieve the objective of load balancing, HA, and no message loss?
> 
> [RebalanceSpec.diff.txt](https://github.com/akka/alpakka-kafka/files/4084710/RebalanceSpec.diff.txt)

If I were to redesign this test I would:

1. Use the `TestProbe` to consume all `Sources` and start them for each consumer you add.  The first consumer would consume 10, the second 5, the third 3 or 4.  While this is happening, previously created consumers may fully process messages and shutdown partitions as complete, after they complete they'll be re-emitted.  As the group rebalances partitions may be shutdown or added too.
2. Add a delay after we wait for the consumer group assignment completes, to allow for some processing.
3. Add some conditions in the business logic to make sure we don't consume all the messages too quickly, otherwise we might finish before all your consumers have been added.

However, this is effectively re-implementing some of our own tests in Alpakka Kafka, as well as tests that exist in the upstream Kafka project that test guarantees of the various consumer group rebalance strategies.

**Comment by seglo** [comment]
> 1. Use the `TestProbe` to consume all `Sources` and start them for each consumer you add.  The first consumer would consume 10, the second 5, the third 3 or 4.  While this is happening, previously created consumers may fully process messages and shutdown partitions as complete, after they complete they'll be re-emitted.  As the group rebalances partitions may be shutdown or added too.

Another way to do this would be to not use the `TestProbe` at all, run the sub-source within the stream (as you did before), and use a `Sink.ignore` for the outer stream.  That way sub-sources wil always be emitted and run.  Then within the logic you could access some threadsafe code to increment counts for fully processed partitions.

**Comment by jhooda** [comment]
@ennru I did modifications in Spec as per your suggestions and it is looking very promising. I'm doing more rigorous tests and will send you a pull request as soon as I am done with them. Thanks.

**Comment by seglo** [comment]
@jhooda That's great.  Sure, feel free to create PRs.  Do you mind if I close this and #1016 in the mean time?

**Comment by jhooda** [comment]
@seglo Yes please go ahead and close this. There are definitely some issues with using "committablePartitionedSource.mapAsyncUnordered / Committer.sink" pattern Vs. "committablePartitionedSource.map / Committer.batchFlow" pattern. The later pattern is stable and without issues. I'll submit a fresh PR for the later pattern. Thanks.

**Pull request closed without merging**
