### PR TITLE
Filtering of messages in transactional source buffer on revoke (#1062)

### PR DESCRIPTION
**Pull request by szymonm**
References #1062

### CODE REVIEW

**Comment by seglo** [comment]
To carry on what I mentioned in #1062, I'm going to run our integration tests locally for a little while to be safe.  What I'm doing is doing repeated loops of the `TransactionsSpec` in the tests integration test project.

```
tests/testOnly *.TransactionsSpec -- -DtimesToRepeat=100
```

I'm also going to bump up the number of test elements in the `provide consistency when multiple transactional streams are being restarted` test a few orders of magnitude.  I'll start with 10 million.

**Comment by seglo** [comment]
Coincidentally, the command I mentioned above will also run the `TransactionsSpec` in the normal test scope, which can't hurt!

**Comment by seglo** [comment]
On second thought.  I'll add a temp task to the travis build to do this instead.

**Comment by szymonm** [comment]
Can you run the same configuration on master?

**Comment by seglo** [comment]
> Can you run the same configuration on master?

Yes, I'll use the #1065 to do both.

**Comment by patriknw** [comment]
@szymonm Seems like this has been stale for a long while. Shall we close as obsolete?

**Comment by szymonm** [comment]
Yes, I'm not convinced of this change anymore.

**Pull request closed without merging**
