### PR TITLE
Add Committer flowWithContext which emits the elements downstream

### PR DESCRIPTION
**Pull request by hayasshi**
I think https://github.com/akka/alpakka-kafka/issues/1203#issuecomment-842402275
And I tried implement [#1203 idea](https://github.com/akka/alpakka-kafka/issues/1203#issuecomment-698282837).

Please review it? @ennru , @seglo

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @hayasshi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by hayasshi** [comment]
@lightbend-cla-validator 
I signed it.

> https://www.lightbend.com/contribute/cla

**Comment by ennru** [comment]
Thank you for giving this a go!
You need to be careful not to break binary compatibility compared to the 2.1.0 release. Some of your API changes seem to do that as Mima detects in https://github.com/akka/alpakka-kafka/pull/1371/checks?check_run_id=2701800818#step:6:85

**Comment by hayasshi** [comment]
Oops.
I wasn't thinking about binary compatibility.
`@ApiMayChange` mark was on it, so I overwrote it.
I will fix it.

**Comment by hayasshi** [comment]
I rename new `Committer` APIs, from `flowWithOffsetContext` to `flowWithContext`.
`sbt mimaReportBinaryIssues` command passed on my machine.
Please review it. 🙇

**Comment by hayasshi** [comment]
Thanks for reviewing. I will also propose.

**Pull request closed without merging**
