### PR TITLE
merge offsets instead of grouping them in batch commit

### PR DESCRIPTION
**Pull request by fancywriter**

### CODE REVIEW

**Comment by fancywriter** [comment]
@ennru @2m , I am trying to run the same test locally which failed on travis and see the strange error message
```
[error] java.lang.IllegalArgumentException: Host name may not be null
[error] 	at org.apache.http.util.Args.containsNoBlanks(Args.java:81)
[error] 	at org.apache.http.HttpHost.<init>(HttpHost.java:81)
[error] 	at org.glassfish.jersey.apache.connector.ApacheConnector.<init>(ApacheConnector.java:255)
[error] 	at org.glassfish.jersey.apache.connector.ApacheConnectorProvider.getConnector(ApacheConnectorProvider.java:115)
[error] 	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:425)
[error] 	at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:90)
[error] 	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:122)
[error] 	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
[error] 	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
[error] 	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:733)
[error] 	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:286)
[error] 	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:135)
[error] 	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:105)
[error] 	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:101)
[error] 	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:92)
[error] 	at org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:629)
[error] 	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2576)
[error] 	at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:533)
[error] 	at com.github.ehsanyou.sbt.docker.compose.docker.client.DockerClient.getContainers(DockerClient.scala:52)
[error] 	at com.github.ehsanyou.sbt.docker.compose.docker.client.DockerClient.containers(DockerClient.scala:58)
[error] 	at com.github.ehsanyou.sbt.docker.compose.runner.DockerComposeTestRunner.$anonfun$run$1(DockerComposeTestRunner.scala:51)
[error] 	at com.github.ehsanyou.sbt.docker.compose.helpers.package$.process(package.scala:37)
[error] 	at com.github.ehsanyou.sbt.docker.compose.runner.DockerComposeTestRunner.run(DockerComposeTestRunner.scala:47)
[error] 	at com.github.ehsanyou.sbt.docker.compose.DockerCompose$.$anonfun$dockerComposeTestImpl$2(DockerCompose.scala:159)
[error] 	at sbt.std.FullInstance$.$anonfun$flattenFun$3(TaskMacro.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (tests / dockerComposeTest) java.lang.IllegalArgumentException: Host name may not be null
```

What did I forget to do?

**Comment by 2m** [comment]
What are you running from sbt? This should work:

```
tests/dockerComposeTest it:testOnly *.PartitionedSourceFailoverSpec
```

**Comment by ennru** [comment]
Thank you for this PR!
Your changes make sense, would you mind describing what made you suggest them?

**Comment by fancywriter** [comment]
@ennru the comment `// Not very efficient` inside made me to think that it could be improved. :smile: 
However, tests still fail - I managed to run it locally, it fails to - maybe I did something wrong or the test itself could be wrong - didn't have enough time to look at this deeper.

The idea is that we can merge offsets before committing and commit only the latest one. :thinking: it should be enough if I correctly understand how kafka and consumer group offsets work.

**Comment by patriknw** [comment]
I haven't looked into the details of this proposal but isn't existing `CommittableOffsetBatchImpl.update` already keeping only one offset per groupId/topic/partition?

**Comment by ennru** [comment]
@fancywriter The "not very efficient" says that `groupedWeightedWithin` builds a sequence while grouping which than is passed to `CommittableOffsetBatch.apply`. In a perfect world, we would construct maps keeping just the highest offsets during grouping already.

**Comment by patriknw** [comment]
> In a perfect world, we would construct maps keeping just the highest offsets during grouping already.

Would that matter much? Aren't these offset handles rather light weight?

**Comment by ennru** [comment]
No, in extremely high throughput scenarios it might be measurable, but not much more.

This PR does not change that part of constructing commit offset batches.

**Comment by ennru** [comment]
@fancywriter While I see a few improvements to the existing code in this PR, I don't think it adds anything important. The committing logic is quite involved and I don't want to change it without a strong case.
I suggest we'd close this and do some minor improvements where suitable instead.

**Comment by fancywriter** [comment]
👌

**Pull request closed without merging**
